# This is a basic workflow that is manually triggered

name: Manual workflow; test SMS message service

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      phone_number:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Phone number to send SMS to'
        # Default value if no value is explicitly provided
        default: '15403310778' #Stephen's phone number
        # Input has to be provided for the workflow to run
        required: true
      message:
        description: 'Message to send as SMS'
        default: "Hello fren!"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send message
      run: python3 -V
